name: Testcafe Test Execution

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: 'chromium,firefox /tests/**/*.spec.js'
